### ISSUE TITLE
`500 internal server error` sometimes when starting a session

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-benefit-tool#139]
When you haven't used the app in a while and load it up, either in dev or QA, it can error. The solution is to refresh.

TODO: Get error message from logs and add to this ticket

**Comment by rmarow** [comment]
`/favicon.ico:1     Failed to load resource: the server responded with a status of 502 (Bad Gateway)`
`qa.usaon.org/:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)`

**Comment by MattF-NSIDC** [comment]
Where are those coming from? Browser console logs or server-side logs?
