### ISSUE TITLE
Sankey diagram tooltip design

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-benefit-tool#156]
https://docs.google.com/presentation/d/1Fwx6Ri3iU1UDXLxr1c-Iw89bB3Db_CQt/edit#slide=id.g281ad3dafbf_0_27

See slide 7-9 for details!

Some example response objects: https://docs.google.com/spreadsheets/d/1ILQbBu4_43eId86wu3sIz-UKEHaGmaSlF1BCa5j_lmE/edit#gid=532553757

**Comment by hazelshapiro** [comment]
See this newer issue: https://github.com/nsidc/usaon-vta-survey/issues/187

**Comment by mfisher87** [comment]
Closing as duplicate
