### ISSUE TITLE
Populate base template footer

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-benefit-tool#174]
Right now the footer only contains the version number, but it's not clearly offset from the rest of the content. We should consider:

- [x] Use an `<hr />` to separate it from the rest of the content
- [x] Use CSS padding or something to distance it from the rest of the content
- [ ] Populate footer with e.g.:
    - [x] Link to source code repository (#238)
    - [ ] Link to Benefit Tool documentation
    - [ ] Support contact information -- link to GitHub Discussions? I think this is a valuable way to add a support forum to the app. 
    - [x] Copyright owner
    - [ ] Copyright date

**Comment by Sherwin-14** [comment]
Hey, I wanted to know whether the issues highlighted  in point number 2 and 3 are still relevant?

**Comment by mfisher87** [comment]
Hey @Sherwin-14 thanks for asking! I updated the OP with checklists for the completed items. I think it's accurate. I'm assigned to a different project, but I'll be coming back to this in February. I'll be available to respond, I just may be a touch slower :)

**Comment by Sherwin-14** [comment]
I was thinking that maybe I should look up on the issues unchecked on the list, if its okay with you I can start working on this.

**Comment by mfisher87** [comment]
That would be great! But don't feel obligated. We really appreciate your help :heart:

**Comment by mfisher87** [comment]
I went through our first page of issues and updated their labels. Several more are marked with https://github.com/nsidc/usaon-benefit-tool/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 if you feel like looking for tasks that might be fun :) Don't hesitate to @ me, @rmarow , or @hazelshapiro if you need anything, but can't promise speedy responses until February ;)

Thank you again, Sherwin, looking forward to working together more!

**Comment by Sherwin-14** [comment]
I'll just do the ones that i am capable of :)

**Comment by Sherwin-14** [comment]
> Support contact information -- link to GitHub Discussions? I think this is a valuable way to add a support forum to the app.

Hey, i just wanted to know the link to discussions page.

**Comment by mfisher87** [comment]
https://github.com/nsidc/usaon-benefit-tool/discussions

Thanks :)
