### ISSUE TITLE
Add assessment fields to "new assessment" form

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#180]
https://www.usaon.org/apps/benefit-tool/survey/new

This page should include: 

- [x] Title: Unique name of survey
- [x] Description: Narrative description of the survey topic
- [x] ~Year: Allows for repeated analyses to show change over time. Year is sufficiently precise. We should also track timestamps (opened_date, last_modified, published_date), but a user-defined 'year' field would be useful.~ *TODO: Is the "version" field OK?*

    - We decided that the reason for this field is to allow people to filter based on year for repeating surveys e.g. River Watch 2023, but we can use the published date or the created date for that instead. (NOTE: The `version` concept we had discussions previously would be independent of this use case)

- [ ] Hypothetical: Current state or Alternative (possible future) state (checkbox)

    - *We called this field "hypothetical" (boolean) on the node table - do we also want that on the assessment table?* @hazelshapiro 
    - *We decided that we want `hypothetical` at the assessment level just like in the object library*

## Independent features

These tickets are not part of the acceptance criteria for this ticket:

- Private: Can this survey be viewed by non-registered members? (Or should it be restricted to individuals?) #120 
- Tags: This is a user-defined field that admins can and will edit. It creates additional flexibility in the analyis, for example allowing for a regionally- or thematically-focused analysis. #271 
- Respondents: List of respondents with edit-access *this is a functionality change, may need a separate ticket* #66  #67 #70 
- Status: In-progress, Published, Closed, Archived #262

**Comment by mfisher87** [comment]
@hazelshapiro is the `year` field still needed in MVP? Or is that replaced with `version`? We've also moved several checkboxes to independent tickets. Can you ensure those tickets are correctly milestoned?

**Comment by hazelshapiro** [comment]
I don't see that there is a version field. Can you clarify? The tickets look correctly milestoned - thank you! But I don't think that the "tags" field is captured anywhere.

**Comment by mfisher87** [comment]
>I don't see that there is a version field

I meant conceptually; I believe we'd talked about a "version" field as a more abstract alternative to a "year" field, and we could use the "title" field to communicate the distinction between versions of the same assessment. E.g., if you're looking at a versioned assessment it might display as: `Assessment #1 (v3): River Watch 2026` (assuming v1 was 2024).

**Comment by mfisher87** [comment]
>But I don't think that the "tags" field is captured anywhere

Created https://github.com/nsidc/usaon-benefit-tool/issues/271

**Comment by mfisher87** [comment]
Oh, and could you also comment on the "Type" field in the top-level post? I added a question there that should have been a comment, my bad 😓
