### ISSUE TITLE
Fix errors in data model

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-benefit-tool#21]
- [ ] Move data product performance rating to application table
- [ ] Add notes field to relationship between application and SBA
- [x] `contribution_to` fields should be `criticality`
- [x] `satisfaction` fields should be `performance`
- [ ] Separate fields for "rationale": One for criticality, one for performance
- [ ] Review notes document and thread for more errors https://nsidc.slack.com/archives/C045Y53PP4L/p1666127765240169

**Comment by MattF-NSIDC** [comment]
Also, consider adding FK for `response_id` to relationships to ensure that no cross-response relationships are created.

**Comment by hazelshapiro** [comment]
Update data model to match metadata fields: https://docs.google.com/spreadsheets/d/1ILQbBu4_43eId86wu3sIz-UKEHaGmaSlF1BCa5j_lmE/edit#gid=0
(nearly final as of April 28 -- Hazel will add another comment when it's complete)

**Comment by rmarow** [comment]
Closed as OVE because we redid the data model, and many of these features are no longer relevant at this time.
