### ISSUE TITLE
Change "Surveys" in top menu to "Projects"

### ISSUE THREAD

**Issue by mfisher87** [nsidc/usaon-benefit-tool#217]
@hazelshapiro I wasn't sure about this one so I made it its own issue. "My projects" implies things specific to that user. Should we be filtering the results down in some way before we make this name change? Maybe this ticket should be combined with another feature ticket.

**Comment by hazelshapiro** [comment]
Maybe "explore projects" for now, or just "projects." I do think updating this to Edit my Projects after the filtering is sorted makes sense

**Comment by mfisher87** [comment]
:+1: Sorry if I forgot a prior discussion, but are we generally changing terminology from "Survey" -> "Project"?

**Comment by hazelshapiro** [comment]
I'm guessing users will relate to this more easily as a project than a survey, but I don't want to do a deep dive overhaul until I know that that is true. Could we change it in the obvious places on the U/I for now, and make an issue to revisit this question when we pick the project back up? I'll be able to run it by some testers in the meantime.

**Comment by mfisher87** [comment]
>I'm guessing users will relate to this more easily as a project than a survey, but I don't want to do a deep dive overhaul until I know that that is true

:100:  see issue #228!
