### ISSUE TITLE
Docker build fails on Fedora when firewall ports closed; document the workaround

### ISSUE THREAD

**Issue by mfisher87** [nsidc/usaon-benefit-tool#239]
See https://github.com/nsidc/usaon-benefit-tool/issues/227#issuecomment-1868377774

**Comment by Sherwin-14** [comment]
Oh yeah, I was testing the build last night and it seems the upgrade of the base image fixed the build issue on Arch. I haven't yet tested on Fedora.

**Comment by mfisher87** [comment]
This change fixed it on Arch for you?

https://github.com/nsidc/usaon-benefit-tool/commit/ea32471fad1251d0264cf71893d8020d553217b2

It didn't work for me on Fedora :( I'm confused! I've never had this problem of a Docker image failing to build on some distros but not others.

**Comment by Sherwin-14** [comment]
It seems so that it did. There are some alternatives to Docker like [Nix](https://nixos.org) you can look at it if Docker is too problematic :)

**Comment by mfisher87** [comment]
I've been wanting to learn Nix for years now, but haven't found the time :laughing:

**Comment by Sherwin-14** [comment]
Hm, so I was messing around with Docker and while trying to get it work on OpenSUSE which was (kind of) suffering from the same problem, I initially thought the error was SELinux however I think, it may be due to the firewall? because OpenSUSE and Fedora utilise the same firewall which might block the port by default? In my case, opening port 8080 and 5000 through my firewall ended up somehow magically making it work.

**Comment by mfisher87** [comment]
:exploding_head: wow, that's not what I expected! Nice find! Maybe we should create a `TROUBLESHOOTING.md` document in case anyone else struggles with it.

**Comment by Sherwin-14** [comment]
I'll try running this on a Fedora VM and see if this works on that as well.

**Comment by Sherwin-14** [comment]
Hey, I just wanted to inform you that it works in Fedora. Somehow the previous error fixed itself .  I''ll be working on the md file now.

**Comment by mfisher87** [comment]
Amazing, thanks @Sherwin-14 !

**Comment by mfisher87** [comment]
Do you agree we can close this issue?

**Comment by Sherwin-14** [comment]
Yes I think we should close it.

**Comment by mfisher87** [comment]
Thanks :)
