### ISSUE TITLE
Update "edit this page" link on quarto

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#242]
Note: non-urgent change

Read-the-docs (quarto) edit this page redirects to the wrong link. 

See: https://usaon-benefit-tool.readthedocs.io/en/latest/reference/decision-records/

Click: "Edit this page"

Goes to: https://github.com/nsidc/usaon-benefit-tool/edit/main/reference/decision-records/index.md

Should be corrected to: https://github.com/nsidc/usaon-benefit-tool/blob/main/doc/reference/decision-records/index.md

**Comment by mfisher87** [comment]
Great catch, thank you! That should be a quick fix if I remember correctly.

**Comment by Sherwin-14** [comment]
I am working on this one.

**Comment by mfisher87** [comment]
Thank you, Sherwin :) Resolved by #244 :partying_face: :rocket:
