### ISSUE TITLE
Some users get error on login: `Access blocked: usaon.org has not completed the Google verification process`

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#252]
I just shared the link for the tool with a colleague and she wrote back with this info...

**Toni:** Also, you mentioned in your messages to Meredith there’s an error going on when trying to log onto the Benefit Tool. Is this what is showing up for people across the board: “Access blocked: [usaon.org](http://usaon.org/) has not completed the Google verification process. The app is currently being tested, and can only be accessed by [developer](https://accounts.google.com/)-approved testers. If you think you should have access, contact the developer.” (edited) 

**Hazel:** No that's new, what did you do to get to that screen?

**Toni:** So I used this link: https://www.usaon.org/apps/benefit-tool/ and then clicked “Log In.” From there, on the “Choose an account
to continue to usaon.org” page, I chose my IARPC account (which is a google account). Then that error pops up

**Comment by mfisher87** [comment]
What the _heck?_ Did Google add some new checkbox I need to tick? :confused:

Is everyone else successfully registering and authenticating, and only this one person is having difficulty?

**Comment by hazelshapiro** [comment]
I was able to log in without a problem - let me see if I can get someone else to try making a new account

**Comment by hazelshapiro** [comment]
Alas, another of my coworkers ran into the same issue

**Comment by mfisher87** [comment]
Anything in common with their Google acconts? Is it possible both users are part of a (the same?) managed domain?

For example, at CU we all get Google accounts, and the admins retain some level of control over those accounts, and sometimes that means setting policies users can't change. Perhaps, for example, a google policy along the lines of "disallow unverified apps" may have been set by these users' admins. In which case, we'll likely have no choice but to figure out how to get Google-verified.

Another option is to allow an alternate SSO provider so the user could choose between Google and GitHub, for example.

**Comment by hazelshapiro** [comment]
Yes they are both iarpccollaborations.org accounts - the odd thing is that that is my domain too!On Jan 23, 2024, at 7:41 AM, Matt Fisher ***@***.***> wrote:﻿
Anything in common with their Google acconts? Is it possible both users are part of a (the same?) managed domain?
For example, at CU we all get Google accounts, and the admins retain some level of control over those accounts, and sometimes that means setting policies users can't change. Perhaps, for example, a google policy along the lines of "disallow unverified apps" may have been set by these users' admins. In which case, we'll likely have no choice but to figure out how to get Google-verified.
Another option is to allow an alternate SSO provider so the user could choose between Google and GitHub, for example.

**Comment by mfisher87** [comment]
Maybe it's a new restriction that only applies at registration time, and you coincidentally registered before the admins added the restriction?

Or maybe it's a personal setting on those accounts that these users set themselves, but didn't know it would cause this. :thinking:

**Comment by mfisher87** [comment]
My initial research hasn't got me closer to understanding why someone might see this error. Our app doesn't require Google verification because it doesn't require any sensitive info from Google:

![Image](https://github.com/nsidc/usaon-benefit-tool/assets/3608264/2e0ada0c-7dbf-44ce-a0c2-77113798d1ee)

**Comment by mfisher87** [comment]
@hazelshapiro since we don't know if it's still happening, and our app seems to currently be configured correctly, I'm going to close this issue. Please re-open if I'm mistaken!
