### ISSUE TITLE
Line color should vary by performance

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#254]
Right now just the object box colors change with performance, but the performance should be reflected in the line color. Related #189 

![image](https://github.com/nsidc/usaon-benefit-tool/assets/119694751/48939876-28ae-4e53-978c-71655e7dcdcf)

Here the line between SSMI/I-SSMIS and Sea Ice Age should reflect the performance score of "7" (brown -- very low on a scale of 0-100). The line between the  SSMI/I-SSMIS and Sea Ice Concentration should reflect the performance score of "50" (orange -- medium performance). The SSMI/I-SSMIS object should be a weighted average performance score. 

The color of the Sea Ice Age and Sea Ice Concentration boxes is defined by how well those data products support the relevant application. See math here: 

![image](https://github.com/nsidc/usaon-benefit-tool/assets/119694751/73ad94e7-c3ba-4c28-b2d5-aaa953a2e758)

![image](https://github.com/nsidc/usaon-benefit-tool/assets/119694751/2f89b222-4aaa-434a-ab9b-de8c8ddb264d)

**Comment by mfisher87** [comment]
The box colors are actually random because we haven't implemented this feature, so I moved this from the "bug fixes" milestone.
