### ISSUE TITLE
Users can't edit their own profiles

### ISSUE THREAD

**Issue by mfisher87** [nsidc/usaon-benefit-tool#288]
Should be a quick fix by adding a conditional around the access check, pseudocode:

```python
if current_user.id != request.form.id:
    forbid_except_for_roles(admin)
```

**Comment by Hira-Ijaz** [comment]
@mfisher87 I would like to work on this issue, please assign it to me.

**Comment by mfisher87** [comment]
@Hira-Ijaz that's awesome! Welcome to our project :heart: :)

Please let me know if there's anything I or @rmarow (developers) or @hazelshapiro (designer) can do to support you.

You may find this document useful along the way: https://usaon-benefit-tool.readthedocs.io/en/latest/how-to/development.html
