### ISSUE TITLE
Assessment and object library description character limit is too small - increase 8x 

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#292]
Increase character/word limit on assessment description. This also applies to objects. 
New Assessment > Description. 
New Observing System/Data Product/Application/Societal Benefit Area > Description.

Increase 8x

**Comment by hazelshapiro** [comment]
@Sherwin-14 if you're interested, this might be another one to tackle. I would want to know from @MattF-NSIDC if it will cause issues with storage space, though, and, Matt, what you would recommend for a new character limit. If these are preset fields, like in a Google form, I'd recommend changing it from a "short answer" to a "long answer" field. Does that make sense?

**Comment by mfisher87** [comment]
@hazelshapiro this doesn't cause me any concerns storage space, let's go with whatever limit feels appropriate to you. Does 4x sound OK?

**Comment by hazelshapiro** [comment]
Great, in that case, let's do 5x so we can accommodate a few longer answers if needed

**Comment by mfisher87** [comment]
>5x

How about 8x? I like multiples of 2 ;)

@hazelshapiro important to note, now that we're in production we _must_ set up data migrations before our next release. The time cost might be a day, two on the outside.

**Comment by Sherwin-14** [comment]
Yes I would love to! Will take a look into it.

**Comment by mfisher87** [comment]
Resolved in #301

**Comment by hazelshapiro** [comment]
Thank you!

**Comment by hazelshapiro** [comment]
> > 5x
> 
> How about 8x? I like multiples of 2 ;)
> 
> @hazelshapiro important to note, now that we're in production we _must_ set up data migrations before our next release. The time cost might be a day, two on the outside. This ticket impacts the data model (see labels). We can only release changes that don't impact the datamodel without needing a migration.
> 
> Edit to add: Future migrations won't re-incur the same setup cost.

Does this mean that this change won't be deployed until we have our next dedicated development time? Just want to make sure I understand. What about deploying the gray nodes update? @mfisher87

**Comment by mfisher87** [comment]
Correct, this change would be impossible to deploy before we figure that problem out. The gray node change is possible to deploy before then, but it does take a nominal amount of time.
