### ISSUE TITLE
Why does the SBA "add new object" have a second "title" field?

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#294]
We do want to be able to add other SBAs -- let's discuss this. See "+ New Societal Benefit Area"

**Comment by mfisher87** [comment]
There are two "SBA" things in the DB. There's the SBA "framework", which exists as static data that nobody is allowed to change. Then, if you want to add an SBA from the framework to the object library, you have the option to then make changes you might want, e.g. override the title. Right now `title` is a field we consider to be "common" for all types of things in the object library, including SBAs, but it doesn't have to be that way if know for sure you always want to re-use the static title in the framework.

If that answers all your questions, do you want to close this or re-title the issue to address the "add other SBAs" need?

**Comment by hazelshapiro** [comment]
I need to better understand the implications of having a static framework in the database & what does that make possible & what would be different about adding other SBAs more dynamically. But broadly, yes, there are probably two issues in this one: (1) adding other SBAs and (2) updating the way the existing SBAs display so there are not two title fields

**Comment by hazelshapiro** [comment]
Moving this to response object registry/library since it impacts how the SBA portion of the library works

**Comment by mfisher87** [comment]
TODO: @hazelshapiro @rmarow bring over notes from Slack: https://nsidc.slack.com/archives/C044NJR3W4B/p1727812992701029?thread_ts=1727811154.191939&cid=C044NJR3W4B

**Comment by mfisher87** [comment]
This is really "we need to polish the SBA design and support multiple frameworks".

**Comment by hazelshapiro** [comment]
Copied the information over in a new issue #327. Suggest we close this question as answered and work from that issue.
