### ISSUE TITLE
Add additional fields to "add link" page

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#295]
Should include three text description boxes (and new fields on the `Link` model):
- Performance rationale: 8192 char limit
- Criticality rationale: 8192 char limit
- Gaps: 8192 char limit
- "Variable or attribute": E.g. "I'm only looking at Wind Speed from this Observing System (weather station)" text, 512

For later:

- Rated by: The person who rated the link. _TBD: How to determine this value? The first person to apply the rating, or the most recent person to update the rating? Allow the value to be selected from a dropdown? Determine it automatically, but allow admins to override (I would consider this a separate feature; for the purpose of this ticket let's pick only one thing)?_

See glossary for more info

**Comment by Sherwin-14** [comment]
@mfisher87 Is this still relevant? Do you have any specific opinions regarding this?

**Comment by mfisher87** [comment]
Hey @Sherwin-14 :) This is still relevant. Looks like we currently only have performance and criticality rating, but we need to add rationale:

https://github.com/nsidc/usaon-benefit-tool/blob/7b8cec64605372c451d55af817607c0e47c5bf13/usaon_benefit_tool/models/tables.py#L398-L413

I am updating the issue description to include what I know. I'm thinking we could create a constant (if there isn't already one) so we can update all the large text fields at once, e.g. `DB_TEXT_SIZE_LARGE = 8196`, and similar constants for the other common string lengths we use. That way it will be easier to change them if we get them wrong :) 

@hazelshapiro I'm adding some "TBD" markers to the issue description. Can you fill those in?

**Comment by hazelshapiro** [comment]
Character limits above look good. 
Variable/attribute: from the glossary - "If an observing system or data product contains many observable properties or variables, this allows a respondent to specify which field they used." Logistically it would be a text field with a ~300 char limit
Rated by: Allow the value to be selected from a dropdown

- Future feature: Limit the 'rated by' feature to the analysts assigned to an assessment, but allow admins to override or enter a name as an 'other' field

**Comment by hazelshapiro** [comment]
Another option would be to have the 'rated by' as an assessment level detail, rather than associated with each individual rating. 
This is linked to: https://github.com/nsidc/usaon-benefit-tool/milestone/
Let me confirm with Sandy, but I think this approach would simplify things and be sufficient. And as a best practice, we would add a description at the assessment level that includes who was responsible for what piece of the rating. 
Let's remember to add a note to the decision record.

**Comment by hazelshapiro** [comment]
Moving this to the response object milestone since it has to do with how analysts enter data. That way we can keep this milestone as projects that are mostly on my list.
