### ISSUE TITLE
Support linking objects of the same type

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#296]
See this image in the glossary. Observing systems, data products, and applications should all be able to support objects of the same type (e.g. one application can support another application)

<img width="899" alt="image" src="https://github.com/nsidc/usaon-benefit-tool/assets/119694751/9a3b899f-9ce9-4dc6-b599-2627796170c5">

**Comment by mfisher87** [comment]
The data model does allow this, we just need to change the code. Should anything change about the visualization? If we don't change anything, there will be cases where nodes of one type will be aligned with nodes of another type.

**Comment by mfisher87** [comment]
Split appearance off to #324
