### ISSUE TITLE
Change default node color to gray

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#297]
Right now the "nodes" in the sankey diagrams are randomly colored. It is visually distracting. Could we change this to gray with hex code 
AEAEAE ?

**Comment by hazelshapiro** [comment]
@MattF-NSIDC I wonder if this would be a good issue for @Sherwin-14 to take on??

**Comment by Sherwin-14** [comment]
Yes I would love to! I'll take a look at it.

**Comment by hazelshapiro** [comment]
Thank you @Sherwin-14!

**Comment by mfisher87** [comment]
Amazing :heart_eyes_cat:

**Comment by mfisher87** [comment]
Thanks again @Sherwin-14 for your great work :100: 

![image](https://github.com/nsidc/usaon-benefit-tool/assets/3608264/38b94844-37a1-4c31-b050-01901bea1554)

**Comment by hazelshapiro** [comment]
Hooray, thank you @Sherwin-14! 😄
