### ISSUE TITLE
Polish the SBA design and support multiple frameworks

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#327]
Ideal design for adding a SBA to an assessment:

- Assuming >1 framework in the Benefit Tool; first ask which framework?
- Enforce that the framework is the same for the whole assessment. Admins pick the framework when creating an assessment. This should be editable once the assessment is created. 
- Choose a top-level SBA hierarchy member, and rating it.
- Select from a list which sub-elements (from the lowest level) of the hierarchy member are important
- Matt: Can they ever select from the middle level? Hazel: I don't know! This is how we do it now.
- Can provide notes on why they chose that.

A design which treats SBAs as any other object in the library, with an extension to support admins managing a list of "child elements" (a list of strings, which could be delimited by /, for example, when there are multiple layers of child elements). Then respondents, when adding an SBA, will be presented with checkboxes for child elements they want to call out as important.

Current "+ a Societal Benefit Area" in the Tool has a redundant SBA and Title field so we also need to clean that up.

**Comment by hazelshapiro** [comment]
NOTE: We also have issue #176. I wonder if that functionality (envisioned for non-SBA objects) would have utility here. If we could implement one solution that would solve both these issues rather than having a separate approach to each.

**Comment by mfisher87** [comment]
@hazelshapiro would you say this supercedes #293 ?

**Comment by mfisher87** [comment]
I saw your comment over there now :) If it seems reasonable to you to close an issue, feel free to go ahead and do that. We'll get notified and if we disagree with the closing we can always re-open!

**Comment by hazelshapiro** [comment]
Sandy is recommending that we keep the SBAs at the highest level only, with an easy way to access the full framework. And adding the capability to attach a document to a spreadsheet with more information.

**Comment by mfisher87** [comment]
>Sandy is recommending that we keep the SBAs at the highest level only

I.e. links can only attach to the top-level SBA, e.g. Food Security, but not sub-areas or key objectives?

>with an easy way to access the full framework. 

What's meant by "access" here? View only? I.e. the description for an SBA could contain the sub-areas and key-objectives, and that would meet this requirement? 

>And adding the capability to attach a document to a spreadsheet with more information.

Spreadsheet?

**Comment by hazelshapiro** [comment]
> > Sandy is recommending that we keep the SBAs at the highest level only
> 
> I.e. links can only attach to the top-level SBA, e.g. Food Security, but not sub-areas or key objectives?
Yes
> 
> > with an easy way to access the full framework.
> 
> What's meant by "access" here? View only? I.e. the description for an SBA could contain the sub-areas and key-objectives, and that would meet this requirement?
Right now the description contains a URL link - that would be sufficient
> 
> > And adding the capability to attach a document to a spreadsheet with more information.
> 
> Spreadsheet?
Oops! I was trying to do too many things at once. Attach a document to an ~~spreadsheet~~ **assessment**

**Comment by rmarow** [comment]
make it an enterable field. Add framework

**Comment by rmarow** [comment]
users will enter an SBA like they might enter another type with a framework field. This is a database change. Concern is current assessments.

**Comment by hazelshapiro** [comment]
> users will enter an SBA like they might enter another type with a framework field. This is a database change. Concern is current assessments.

Fields for SBA:

- [ ] Name
- [ ] Short name
- [ ] Description
- [ ] Framework name
- [ ] Framework URL:

**Comment by rmarow** [comment]
@hazelshapiro for these fields which are okay to be null? My assumption is:
 Name: nullable=false
 Short name: nullable=True
 Description: nullable=False
 Framework name: nullable=False
 Framework URL: nullable=True

**Comment by rmarow** [comment]
Due to shared node fields these are the fields - only noticeable difference should be Name==Title @hazelshapiro 
<img width="795" alt="Screen Shot 2024-10-15 at 4 57 18 PM" src="https://github.com/user-attachments/assets/5b6890e0-d16f-45ca-951a-45b104bba56e">

**Comment by hazelshapiro** [comment]
What I understand is that you can't have two "Name" fields during the transition to this new structure, so you had to rename this field as "Title." Is that right? Not a problem, though maybe in a later version we can change it back to "Name"

**Comment by rmarow** [comment]
@hazelshapiro we actually can add a name field , but cannot remove the Title field since that is shared across all nodes

**Comment by hazelshapiro** [comment]
Yes, no need for both name and title
