### ISSUE TITLE
Must click "login" twice to see profile/logout button

### ISSUE THREAD

**Issue by rmarow** [nsidc/usaon-benefit-tool#58]

**Comment by rmarow** [comment]
As of today not seeing this issue in DEV, need to retest in QA

**Comment by rmarow** [comment]
release v0.2.0 to see

**Comment by rmarow** [comment]
This has been oddly sporadic in DEV atleast. Sometimes twice is needed, sometimes only once.

**Comment by MattF-NSIDC** [comment]
Does it maybe correspond with the server reloading after a change?

**Comment by MattF-NSIDC** [comment]
Or maybe with an expired token?
