### ISSUE TITLE
Support database backup and restore

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-benefit-tool#79]
* Enable us to dump the database and restore from the same dump.
* Schedule a daily (?) rotating database backup

**Comment by hazelshapiro** [comment]
Focus on the most basic version for this development sprint. After this is done - create another issue in [2 - Robust data management: enable AON to begin data entry in production](https://github.com/nsidc/usaon-benefit-tool/milestone/10)

**Comment by mfisher87** [comment]
Created #322

**Comment by mfisher87** [comment]
https://github.com/nsidc/usaon-benefit-tool-db/pull/2

Waiting to see if the rotation works as expected overnight.

**Comment by mfisher87** [comment]
Everything is working!
