### ISSUE TITLE
Ensure app is served by HTTPS by production webserver

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-benefit-tool#87]
Until we have a more permanent org-wide solution, we should add an Nginx or Traefik reverse proxy container to our non-dev stack with a self-signed certificate.

I think the `hermes-webserver` project in Bitbucket provides an example of how to set up the reverse proxy container. The `hermes-stack` repo shows how it integrates with the other elements of the stack.

**Comment by rmarow** [comment]
Thinking NGINX will be the way to go.
